name: "sweetdreamer-stage1"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 0
use_timestamp: false

data_type: "random-camera-datamodule"
data:
  batch_size: 8
  width: 64
  height: 64
  camera_distance_range: [1.4, 1.6]
  fovy_range: [35, 45]
  elevation_range: [-10, 45]
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.
  eval_camera_distance: 1.5
  eval_fovy_deg: 35
  n_val_views: 4

system_type: "sweetdreamer-system"
system:
  start_app: 1500
  before_start_app_weight: 0.0
  app_weight: 1.0
  end_app: 100000
  after_end_app_weight: 1.0

  start_cmm: 0
  before_start_cmm_weight: 0.0
  cmm_weight: 20.0
  end_cmm: 1500
  after_end_cmm_weight: 1.0

  geometry_type: "implicit-volume"
  geometry:
    radius: 2.0
    isosurface: true
    isosurface_method: "mc-cpu"
    isosurface_resolution: 64
    isosurface_threshold: "auto"
    isosurface_coarse_to_fine: false
    normal_type: "finite_difference"

    density_bias: "blob_magic3d"
    density_activation: softplus
    density_blob_scale: 10.
    density_blob_std: 0.5

    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.447269237440378 # max resolution 4096

  material_type: "no-material"
  material:
    n_output_dims: 3
    color_activation: sigmoid
    requires_normal: true

  background_type: "neural-environment-map-background"
  background:
    color_activation: sigmoid
    random_aug: true
    random_aug_prob: 0.5

  renderer_type: "nerf-volume-renderer"
  renderer:
    radius: ${system.geometry.radius}
    num_samples_per_ray: 512
    return_comp_normal: true

  prompt_processor_type: "deep-floyd-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    negative_prompt: "worst quality, normal quality, low quality, low res, blurry, text, watermark, logo, banner, extra digits, cropped, jpeg artifacts, signature, username, error, sketch ,duplicate, ugly, monochrome, horror, geometry, mutation, disgusting"
    prompt: ???
    front_threshold: 45.
    back_threshold: 45.
    view_dependent_prompt_front: true
    
  cmm_prompt_processor_type: "stable-diffusion-prompt-processor"
  cmm_prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    negative_prompt: "worst quality, normal quality, low quality, low res, blurry, text, watermark, logo, banner, extra digits, cropped, jpeg artifacts, signature, username, error, sketch ,duplicate, ugly, monochrome, horror, geometry, mutation, disgusting"
    prompt: ???
    front_threshold: 45.
    back_threshold: 45.
    view_dependent_prompt_front: true

  guidance_type: "deep-floyd-guidance"
  guidance:
    cmm_pretrained_model_name_or_path: "ckpt/checkpoint-latent-tiny"
    cmm_schedule_pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    pretrained_model_name_or_path: "DeepFloyd/IF-I-XL-v1.0"
    guidance_scale: 20.
    min_step_percent: 0.02
    max_step_percent: [0, 0.98, 0.5, 5001]
    
  loggers:
    wandb:
      enable: false
      project: "threestudio"
      name: None

  loss:
    lambda_orient: [0, 10., 1000., 5000]
    lambda_sparsity: 0.
    lambda_opaque: 0.
    lambda_z_variance: 0.
  optimizer:
    name: AdamW
    args:
      betas: [0.9, 0.99]
      eps: 1.e-15
    params:
      geometry.encoding:
        lr: 0.01
      geometry.density_network:
        lr: 0.001
      geometry.feature_network:
        lr: 0.001
      background:
        lr: 0.001
      guidance:
        lr: 0.0001

trainer:
  max_steps: 6000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 200
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
